services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: ""
    startCommand: python3 main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CREATOR_CHAT_ID
        sync: false
    plan: free
    autoDeploy: true
